puts "🌱 Seeding Teams..."
Team.destroy_all
MostValuablePlayer.destroy_all
HeadCoach.destroy_all


Team.create(name: "Bills", city: "Buffalo", win: 0,loss: 0, tie: 0)
Team.create(name: "Jets", city: "New York",  win: 0,loss: 0, tie: 0)
Team.create(name: "Dolphins", city: "Miami",  win: 0,loss: 0, tie: 0)
Team.create(name: "Patriots", city: "New England",  win: 0,loss: 0, tie: 0)
Team.create(name: "Chiefs", city: "Kansas City", win: 0,loss: 0, tie: 0)
Team.create(name: "Chargers", city: "LA", win: 0,loss: 0, tie: 0)
Team.create(name: "Raiders", city: "Las Vegas", win: 0,loss: 0, tie: 0)
Team.create(name: "Broncos", city: "Denver",  win: 0,loss: 0, tie: 0)
Team.create(name: "Ravens", city: "Baltimore",  win: 0,loss: 0, tie: 0)
Team.create(name: "Bengals", city: "Cincinatti",  win: 0,loss: 0, tie: 0)
Team.create(name: "Browns", city: "Cleveland", win: 0,loss: 0, tie: 0)
Team.create(name: "Steelers", city: "Pittsburgh",  win: 0,loss: 0, tie: 0)
Team.create(name: "Titans", city: "Tennessee",  win: 0,loss: 0, tie: 0)
Team.create(name: "Colts", city: "Indianapolis",  win: 0,loss: 0, tie: 0)
Team.create(name: "Jaguars", city: "Jacksonville",  win: 0,loss: 0, tie: 0)
Team.create(name: "Texans", city: "Houston",  win: 0,loss: 0, tie: 0)
Team.create(name: "Eagles", city: "Philadelphia",  win: 0,loss: 0, tie: 0)
Team.create(name: "Giants", city: "NY",  win: 0,loss: 0, tie: 0)
Team.create(name: "Cowboys", city: "Dallas", win: 0,loss: 0, tie: 0)
Team.create(name: "Commanders", city: "Washington",  win: 0,loss: 0, tie: 0)
Team.create(name: "Seahawks", city: "Seattle",  win: 0,loss: 0, tie: 0)
Team.create(name: "Rams", city: "Los Angeles", win: 0,loss: 0, tie: 0)
Team.create(name: "49ers", city: "San Fransisco",  win: 0,loss: 0, tie: 0)
Team.create(name: "Cardinals", city: "Arizona",  win: 0,loss: 0, tie: 0)
Team.create(name: "Vikings", city: "Minnesota",  win: 0,loss: 0, tie: 0)
Team.create(name: "Packers", city: "Green Bay",  win: 0,loss: 0, tie: 0)
Team.create(name: "Bears", city: "Chicago",  win: 0,loss: 0, tie: 0)
Team.create(name: "Lions", city: "Detroit",  win: 0,loss: 0, tie: 0)
Team.create(name: "Buccaneers", city: "Tampa Bay",  win: 0,loss: 0, tie: 0)
Team.create(name: "Falcons", city: "Atlanta",  win: 0,loss: 0, tie: 0)
Team.create(name: "Panthers", city: "Carolina",  win: 0,loss: 0, tie: 0)
Team.create(name: "Saints", city: "New Orleans",  win: 0,loss: 0, tie: 0)

puts "Loading Each Team's MVP!🏆"

MostValuablePlayer.create(name: "Aaron Rodgers", position: "QB", year: "2021")
MostValuablePlayer.create(name: "Aaron Rodgers", position: "QB", year: "2020")
MostValuablePlayer.create(name: "Lamar Jackson", position: "QB", year: "2019")
MostValuablePlayer.create(name: "Patrick Mahomes", position: "QB", year: "2018")
MostValuablePlayer.create(name: "Tom Brady", position: "QB", year: "2017")
MostValuablePlayer.create(name: "Matt Ryan", position: "QB", year: "2016")
MostValuablePlayer.create(name: "Cam Newton", position: "QB", year: "2015")
MostValuablePlayer.create(name: "Aaron Rodgers", position: "QB", year: "2014")
MostValuablePlayer.create(name: "Peyton Manning", position: "QB", year: "2013")
MostValuablePlayer.create(name: "Adrian Peterson", position: "RB", year: "2012")
MostValuablePlayer.create(name: "Aaron Rodgers", position: "QB", year: "2011")
MostValuablePlayer.create(name: "Tom Brady", position: "QB", year: "2010")
MostValuablePlayer.create(name: "Peyton Manning", position: "QB", year: "2009")
MostValuablePlayer.create(name: "Peyton Manning", position: "QB", year: "2008")
MostValuablePlayer.create(name: "Tom Brady", position: "QB", year: "2007")
MostValuablePlayer.create(name: "LaDainian Tomlinson", position: "RB", year: "2006")
MostValuablePlayer.create(name: "Shaun Alexander", position: "QB", year: "2005")
MostValuablePlayer.create(name: "Peyton Manning", position: "RB", year: "2004")
MostValuablePlayer.create(name: "Steve McNair", position: "QB", year: "2003")
MostValuablePlayer.create(name: "Peyton Manning", position: "QB", year: "2003")
MostValuablePlayer.create(name: "Rich Gannon", position: "QB", year: "2002")
MostValuablePlayer.create(name: "Kurt Warner", position: "QB", year: "2001")
MostValuablePlayer.create(name: "Marshall Faulk", position: "RB", year: "2000")
MostValuablePlayer.create(name: "Kurt Warner", position: "QB", year: "1999")
MostValuablePlayer.create(name: "Terrell Davis", position: "HB", year: "1998")
MostValuablePlayer.create(name: "Barry Sanders", position: "HB", year: "1997")
MostValuablePlayer.create(name: "Brett Favre", position: "QB", year: "1997")
MostValuablePlayer.create(name: "Brett Favre", position: "QB", year: "1996")
MostValuablePlayer.create(name: "Brett Favre", position: "QB", year: "1995")
MostValuablePlayer.create(name: "Steve Young", position: "QB", year: "1994")


puts "Loading Head Coaches"

HeadCoach.create(name:'Sean McDermott' , team_id:1)
HeadCoach.create(name:'Robert Saleh', team_id:2)
HeadCoach.create(name:'Mike McDaniel' , team_id:3)
HeadCoach.create(name: 'Bill Belichick', team_id:4)
HeadCoach.create(name: 'Andy Reid', team_id:5)
HeadCoach.create(name: 'Brandon Staley', team_id:6)
HeadCoach.create(name: 'Josh McDaniels', team_id:7)
HeadCoach.create(name: 'Nathaniel Hackett', team_id:8)
HeadCoach.create(name: 'John Harbaugh', team_id:9)
HeadCoach.create(name: 'Zac Taylor', team_id:10)
HeadCoach.create(name: 'Kevin Stefanski', team_id:11)
HeadCoach.create(name: 'Mike Tomlin', team_id:12)
HeadCoach.create(name: 'Mike Vrabel', team_id:13)
HeadCoach.create(name: 'Frank Reich', team_id:14)
HeadCoach.create(name: ' Doug Pederson', team_id:15)
HeadCoach.create(name: 'Lovie Smith', team_id:16)
HeadCoach.create(name: 'Nick Sirianni', team_id:17)
HeadCoach.create(name: 'Brian Daboll', team_id:18)
HeadCoach.create(name: 'Mike McCarthy', team_id:19)
HeadCoach.create(name: 'Ron Rivera', team_id:20)
HeadCoach.create(name: 'Pete Carroll', team_id:21)
HeadCoach.create(name: 'Sean McVay', team_id:22)
HeadCoach.create(name: 'Kyle Shanahan', team_id:23)
HeadCoach.create(name: 'Kliff Kingsbury', team_id:24)
HeadCoach.create(name: "Kevin O'Connell", team_id:25)
HeadCoach.create(name: 'Matt LaFleur', team_id:26)
HeadCoach.create(name: 'Matt Eberflus', team_id:27)
HeadCoach.create(name: 'Dan Campbell', team_id:28)
HeadCoach.create(name: 'Todd Bowles', team_id:29)
HeadCoach.create(name: 'Arthur Smith', team_id:30)
HeadCoach.create(name: 'Matt Rhule', team_id:31)
HeadCoach.create(name: 'Dennis Allen', team_id:32)




puts "✅ Done seeding!"
