puts "🌱 Seeding spices..."

t1 = Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")
Team.create (name: "", city: "", record: "")

puts "Loading Each Team's MVP!🏆"

MostValuablePlayer.create (name: "", position: "", team_id: t1)
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )
MostValuablePlayer.create (name: "", position: "", team_id: )




puts "✅ Done seeding!"
