puts "🌱 Seeding Teams..."
Team.destroy_all
MostValuablePlayer.destroy_all


t1 = Team.create(name: "Bills", city: "Buffalo", win_loss_tie: "5-1-0")
t2 = Team.create(name: "Jets", city: "New York", win_loss_tie: "5-2-0")
t3 = Team.create(name: "Dolphins", city: "Miami", win_loss_tie: "4-3-0")
t4 = Team.create(name: "Patriots", city: "New England", win_loss_tie: "3-3-0")
t5 = Team.create(name: "Chiefs", city: "Kansas City", win_loss_tie: "5-2-0")
t6 = Team.create(name: "Chargers", city: "LA", win_loss_tie: "4-3-0")
t7 = Team.create(name: "Raiders", city: "Las Vegas", win_loss_tie: "2-4-0")
t8 = Team.create(name: "Broncos", city: "Denver", win_loss_tie: "2-5-0")
t9 = Team.create(name: "Ravens", city: "Baltimore", win_loss_tie: "4-3-0")
t10 = Team.create(name: "Bengals", city: "Cincinatti", win_loss_tie: "4-3-0")
t11 = Team.create(name: "Browns", city: "Cleveland", win_loss_tie: "2-5-0")
t12 = Team.create(name: "Steelers", city: "Pittsburgh", win_loss_tie: "2-5-0")
t13 = Team.create(name: "Titans", city: "Tennessee", win_loss_tie: "4-2-0")
t14 = Team.create(name: "Colts", city: "Indianapolis", win_loss_tie: "3-3-1")
t15 = Team.create(name: "Jaguars", city: "Jacksonville", win_loss_tie: "2-5-0")
t16 = Team.create(name: "Texans", city: "Houston", win_loss_tie: "1-4-1")
t17 = Team.create(name: "Eagles", city: "Philadelphia", win_loss_tie: "6-0-0")
t18 = Team.create(name: "Giants", city: "NY", win_loss_tie: "5-1-0")
t19 = Team.create(name: "Cowboys", city: "Dallas", win_loss_tie: "5-2-0")
t20 = Team.create(name: "Commanders", city: "Washington", win_loss_tie: "3-4-0")
t21 = Team.create(name: "Seahawks", city: "Seattle", win_loss_tie: "4-3-0")
t22 = Team.create(name: "Rams", city: "Los Angeles", win_loss_tie: "3-3-0")
t23 = Team.create(name: "49ers", city: "San Fransisco", win_loss_tie: "3-4-0")
t24 = Team.create(name: "Cardinals", city: "Arizona", win_loss_tie: "3-4-0")
t25 = Team.create(name: "Vikings", city: "Minnesota", win_loss_tie: "5-1-0")
t26 = Team.create(name: "Packers", city: "Green Bay", win_loss_tie: "3-4-0")
t27 = Team.create(name: "Bears", city: "Chicago", win_loss_tie: "2-4-0")
t28 = Team.create(name: "Lions", city: "Detroit", win_loss_tie: "1-5-0")
t29 = Team.create(name: "Buccaneers", city: "Tampa Bay", win_loss_tie: "3-4-0")
t30 = Team.create(name: "Falcons", city: "Atlanta", win_loss_tie: "3-4-0")
t31 = Team.create(name: "Panthers", city: "Carolina", win_loss_tie: "2-5-0")
t32 = Team.create(name: "Saints", city: "New Orleans", win_loss_tie: "2-5-0")

puts "Loading Each Team's MVP!🏆"

MostValuablePlayer.create(name: "Josh Allen", position: "QB", team_id: 1)
MostValuablePlayer.create(name: "Zach Wilson", position: "QB", team_id: 2)
MostValuablePlayer.create(name: "Tyreek Hill", position: "WR", team_id: 3)
MostValuablePlayer.create(name: "Damien Harris", position: "HB", team_id: 4)
MostValuablePlayer.create(name: "Travis Kelce", position: "TE", team_id: 5)
MostValuablePlayer.create(name: "Justin Herbert", position: "QB", team_id: 6)
MostValuablePlayer.create(name: "Davante Adams", position: "WR", team_id: 7)
MostValuablePlayer.create(name: "Jerry Jeudy", position: "WR", team_id: 8)
MostValuablePlayer.create(name: "Lamar Jackson", position: "QB", team_id: 9)
MostValuablePlayer.create(name: "Joe Burrow", position: "QB", team_id: 10)
MostValuablePlayer.create(name: "Deshaun Watson", position: "QB", team_id: 11)
MostValuablePlayer.create(name: "Minkah Fitzpatrick", position: "S", team_id: 12)
MostValuablePlayer.create(name: "Derrick Henry", position: "HB", team_id: 13)
MostValuablePlayer.create(name: "Johnathan Taylor", position: "HB", team_id: 14)
MostValuablePlayer.create(name: "Travis Etienne Jr.", position: "HB", team_id: 15)
MostValuablePlayer.create(name: "Brandin Cooks", position: "WR", team_id: 16)
MostValuablePlayer.create(name: "Jalen Hurts", position: "QB", team_id: 17)
MostValuablePlayer.create(name: "Saquon Barkley", position: "HB", team_id: 18)
MostValuablePlayer.create(name: "CeeDee Lamb", position: "WR", team_id: 19)
MostValuablePlayer.create(name: "Taylor Heinicke", position: "QB2", team_id: 20)
MostValuablePlayer.create(name: "Geno Smith", position: "QB", team_id: 21)
MostValuablePlayer.create(name: "Cooper Kupp", position: "WR", team_id: 22)
MostValuablePlayer.create(name: "Deebo Samuel", position: "WR", team_id: 23)
MostValuablePlayer.create(name: "Eno Benjamin", position: "HB", team_id: 24)
MostValuablePlayer.create(name: "Dalvin Cooks", position: "HB", team_id: 25)
MostValuablePlayer.create(name: "Aaron Jones", position: "HB", team_id: 26)
MostValuablePlayer.create(name: "David Montgomery", position: "HB", team_id: 27)
MostValuablePlayer.create(name: "T.J. Hockenson", position: "TE", team_id: 28)
MostValuablePlayer.create(name: "Mike Evans", position: "WR", team_id: 29)
MostValuablePlayer.create(name: "Drake London", position: "WR", team_id: 30)
MostValuablePlayer.create(name: "D'Onta Foreman", position: "HB", team_id: 31)
MostValuablePlayer.create(name: "Chris Olave", position: "WR", team_id: 32)




puts "✅ Done seeding!"
